In [5]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [3]:
A.ndim

2

In [6]:
from scipy import linalg
linalg.det(A)

2.999999999999997

A = P L U , 
P=PERMUTED MATRIX 
L=LOWER MATRIX
U=UPPER MATRIX

In [7]:
P,L,U = linalg.lu(A)

In [8]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [9]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [10]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [11]:
np.dot(L,U)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

EIGEN VALUE AND EIGEN VECTORS

In [12]:
EW,EV = linalg.eig(A)
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [13]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])