In [1]:
import numpy as np
a=np.array([1,3,5,7,9])
print()

array([1, 3, 5, 7, 9])

In [4]:
a.shape

(5,)

In [6]:
a=np.linspace(1,100,100)
a

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [7]:
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
a=np.zeros((3,5))

In [16]:
a=np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Generating Random Array

In [22]:
a=np.random.rand(10)*10
a

array([6.64303484, 0.52800374, 8.98631253, 0.96953562, 6.67789902,
       2.53039207, 7.24430234, 6.20310558, 5.38576186, 3.51914085])

In [25]:
a.min()
a.max()

0.5280037357322198

In [26]:
a.argmax()

2

In [27]:
a.max()

8.98631252736055